### ISSUE TITLE
Vimeo tracks don't auto-start anymore

### ISSUE THREAD

**Issue by adrienjoly** [adrienjoly/playemjs#21]
To reproduce:

- clone this repo
- `npm i`
- `npm start`
- go to http://localhost:8000/test/test-track/ and see that the Vimeo track does not play

=> Make it so the track automatically plays. (like in other players)

**Comment by adrienjoly** [comment]
By any chance, do you have an idea why the tracks that follows a Vimeo track sometimes doesn't autoplay, on Openwhyd? (https://github.com/openwhyd/openwhyd/issues/150)

Could this mean that the "end" event is not fired by Vimeo's player anymore?

**Comment by mauricesvay** [comment]
There's a postMessage error at the end. Let's see if this fix also solves that issue.

**Comment by adrienjoly** [comment]
Your fix is now running on openwhyd.org, and it apparently fixes the playback of following tracks as well!

Thanks again for your contribution, Maurice!
